server:
  port: 8771

eureka:
  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: 'http://localhost:8200'
          predicates:
            - Path=/rest/api/user/**
        - id: listing-service
          uri: 'http://localhost:8201'
          predicates:
            - Path=/rest/api/listing/**
        - id: booking-service
          uri: 'http://localhost:8202'
          predicates:
            - Path=/rest/api/booking/**
        - id: chat-service
          uri: 'http://localhost:8200'
          predicates:
            - Path=/rest/api/chat/**