spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/booking_app
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false

server:
  port: 8200

eureka:
  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka